# Generated by Django 3.1.6 on 2021-02-06 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='hide_phone',
            field=models.BooleanField(default=True),
        ),
    ]
