# Generated by Django 3.1.6 on 2021-02-06 10:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_account_hide_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='phone',
            field=models.CharField(max_length=12, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Телефон, должен быть в виде +79119119191 или 89559559595', regex='(?:\\+7|8)(?:\\d{2,3}){4}')], verbose_name='phone'),
        ),
    ]
